# cspell Configuration File

version: "0.2"
language: "en"
dictionaries:
  - python
  - softwareTerms
  - typescript
  - node
ignorePaths:
  - "node_modules/**"
  - "dist/**"
  - ".git/**"
  - ".github/**"
words:
  - Codespace
  - Codespaces
  - docstrings
  - xunit

languageSettings:
  - languageId: "markdown"
    dictionaries:
      - markdown
  - languageId: "python"
    dictionaries:
      - python
overrides:
  - filename: "**/*.md"
    dictionaries:
      - markdown
  - filename: "**/*.py"
    languageId: "python"
    dictionaries:
      - python
